# Generated by Django 3.2 on 2021-04-22 00:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Miscellaneous', '0002_translator_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='translator',
            name='new_language',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='translator',
            name='orgin_language',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='translator',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 0, 21, 27, 452177, tzinfo=utc)),
        ),
    ]
