# Generated by Django 3.2 on 2021-04-30 22:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Miscellaneous', '0008_alter_translator_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translator',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 30, 22, 30, 24, 169922, tzinfo=utc)),
        ),
    ]
