# Generated by Django 3.2 on 2021-05-02 18:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Miscellaneous', '0011_alter_translator_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translator',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 18, 57, 42, 655103, tzinfo=utc)),
        ),
    ]
