# Generated by Django 3.2 on 2021-05-03 14:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Miscellaneous', '0012_alter_translator_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translator',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 14, 34, 11, 607420, tzinfo=utc)),
        ),
    ]
