# Generated by Django 3.2 on 2021-04-15 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=50, null=True)),
                ('message', models.TextField(max_length=1000)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_img', models.ImageField(default='static/Text.png', upload_to='static/Images')),
                ('texter', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=50, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_img', models.ImageField(default='static/Call.png', upload_to='static/Images')),
                ('caller', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
