# Generated by Django 3.2 on 2021-04-16 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Communication', '0003_auto_20210415_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='Whos_Phone',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='contact_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='home_number',
            field=models.CharField(default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='work_number',
            field=models.CharField(default=None, max_length=18),
        ),
    ]
