# Generated by Django 3.2 on 2021-04-19 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Communication', '0008_auto_20210419_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='app_img',
        ),
        migrations.RemoveField(
            model_name='text',
            name='app_img',
        ),
    ]
