# Generated by Django 3.2 on 2021-04-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Communication', '0011_emailing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailing',
            name='your_email',
        ),
        migrations.AddField(
            model_name='emailing',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
