# Generated by Django 3.2 on 2021-05-01 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Communication', '0012_auto_20210419_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=50, null=True)),
                ('target', models.CharField(max_length=50, null=True)),
                ('message', models.TextField(max_length=1000)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
