# Generated by Django 3.2 on 2021-04-28 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Communication', '0012_auto_20210419_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextPing',
            fields=[
                ('text_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Communication.text')),
            ],
            bases=('Communication.text',),
        ),
    ]
