# Generated by Django 3.2 on 2021-05-02 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Communication', '0013_textsave'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender', models.CharField(blank=True, max_length=50, null=True)),
                ('to', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
