# Generated by Django 3.2 on 2021-05-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Communication', '0014_receivedtexts'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='type',
            field=models.CharField(default='sent', max_length=10),
        ),
    ]
