# Generated by Django 3.2 on 2021-05-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Communication', '0015_text_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedtexts',
            name='type',
            field=models.CharField(default='recieved', max_length=10),
        ),
    ]
