# Generated by Django 3.2 on 2021-04-16 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Communication', '0002_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='home_number',
            field=models.CharField(default=None, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='mobile_number',
            field=models.CharField(default=None, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='work_number',
            field=models.CharField(default=None, max_length=18, null=True),
        ),
    ]
