# Generated by Django 3.2 on 2021-04-19 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Communication', '0010_auto_20210419_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('to', models.EmailField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(max_length=50, null=True)),
                ('message', models.TextField(max_length=1000)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('whos_email1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
